meta_product_name: "PractiCo"
meta_title: "PractiCo - Social accountability for skill learning"
meta_description: "Challenge your friends to learn new skills"
meta_image: "login-img.png" # should exist in `app/assets/images/`
